name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'

    - name: Install Dependencies
      run: flutter pub get

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"

    - name: Build Web
      run: |
        flutter build web --release --base-href "/"
        echo "const String buildDate = '${${{ steps.date.outputs.date }}}'" > lib/build_info.dart

    - name: Update index.html
      run: |
        sed -i 's|<head>|<head>\n  <meta name="build-date" content="${{ steps.date.outputs.date }}">|g' build/web/index.html

    - name: Add .nojekyll
      run: touch build/web/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.gptroastsmyinstagram }}
        publish_dir: build/web
        cname: roast-my.site 
        publish_branch: gh-pages
        force_orphan: true